# Generated by Django 4.0.6 on 2022-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False)),
                ('cl_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('cl_email', models.CharField(blank=True, max_length=1000, null=True)),
                ('cl_phone', models.IntegerField(blank=True, null=True)),
                ('cl_address', models.TextField(blank=True, null=True)),
                ('cl_password', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consists',
            fields=[
                ('cn_pr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cn_md_id', models.IntegerField()),
            ],
            options={
                'db_table': 'consists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('dev_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('dev_email', models.CharField(blank=True, max_length=1000, null=True)),
                ('dev_phone', models.IntegerField(blank=True, null=True)),
                ('dev_address', models.TextField(blank=True, null=True)),
                ('dev_password', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'developers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('ex_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('ex_email', models.CharField(blank=True, max_length=1000, null=True)),
                ('ex_phone', models.IntegerField(blank=True, null=True)),
                ('ex_address', models.TextField(blank=True, null=True)),
                ('ex_password', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'experts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fl_id', models.AutoField(primary_key=True, serialize=False)),
                ('fl_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('fl_description', models.TextField(blank=True, null=True)),
                ('fl_file', models.TextField(blank=True, null=True)),
                ('fl_md_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('md_id', models.AutoField(primary_key=True, serialize=False)),
                ('md_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('md_input', models.FileField(upload_to='')),
                ('md_input_file', models.TextField(blank=True, null=True)),
                ('md_description', models.TextField(blank=True, null=True)),
                ('md_output', models.FileField(upload_to='')),
                ('md_output_file', models.TextField(blank=True, null=True)),
                ('md_dev_id', models.IntegerField(blank=True, null=True)),
                ('md_status', models.CharField(max_length=50)),
                ('md_due', models.DateField(blank=True, null=True)),
                ('md_pr_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('pr_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('pr_description', models.TextField(blank=True, null=True)),
                ('pr_due', models.DateField(blank=True, null=True)),
                ('pr_closing', models.TextField(blank=True, null=True)),
                ('pr_file', models.FileField(upload_to='')),
                ('pr_cl_id', models.IntegerField(blank=True, null=True)),
                ('pr_ex_id', models.IntegerField(blank=True, null=True)),
                ('pr_status', models.CharField(max_length=50)),
                ('pr_date', models.DateField()),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
    ]
