# Generated by Django 4.0.6 on 2022-07-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True},
        ),
    ]
