# Generated by Django 4.0.6 on 2022-07-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consists',
        ),
    ]
