# Generated by Django 4.0.6 on 2022-07-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_login', '0002_alter_projects_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pr_progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
