# Generated by Django 4.0.6 on 2022-07-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_login', '0003_projects_pr_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'managed': b'I01\n'},
        ),
    ]
