# Generated by Django 4.0.6 on 2022-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_login', '0004_alter_modules_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='md_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='md_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='md_input_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='modules',
            name='md_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='md_output_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
