# Generated by Django 4.0.6 on 2022-09-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_login', '0006_rename_md_suggestion_modules_md_sugg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='modules',
            name='md_level',
            field=models.CharField(default='beginner', max_length=50),
        ),
    ]
