# Generated by Django 4.0.6 on 2022-09-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_login', '0007_alter_files_options_modules_md_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='fl_input_file',
            field=models.FileField(blank=True, null=True, upload_to='project/modules'),
        ),
        migrations.AddField(
            model_name='files',
            name='fl_output_file',
            field=models.FileField(blank=True, null=True, upload_to='project/modules'),
        ),
        migrations.AlterField(
            model_name='files',
            name='fl_file',
            field=models.FileField(null=True, upload_to='project/modules'),
        ),
        migrations.AlterField(
            model_name='files',
            name='fl_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
