# Generated by Django 4.0.6 on 2022-09-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_login', '0008_files_fl_input_file_files_fl_output_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fl_file',
            field=models.FileField(blank=True, null=True, upload_to='project/modules'),
        ),
        migrations.AlterField(
            model_name='files',
            name='fl_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='md_level',
            field=models.CharField(default='Easy', max_length=50),
        ),
    ]
